Initial version
melexis/traceability-viewer pull request #1
Opened 2023-09-13 15:34 UTC by JokeWaumans

There are still some bugs that need to be fixed, but the main goal is working.

2023-09-14 06:53 UTC, Ben2022 commented on README.md
> +Change the `BASE_URL` in the `config.yml` file to the correct path on you're computer.
```suggestion
Change the `BASE_URL` in the `config.yml` file to the correct path on your computer.
```

2023-09-14 06:55 UTC, Ben2022 commented on autocomplete.py
> +
Generally speaking, I think we need more comments explaining what we do.

2023-09-14 06:57 UTC, Ben2022 commented on make_html.py
> +Python module to make the html files of the traceabilitytool with the accompanying data to start with.
```suggestion
Python module to make the html files of the traceability tool with the accompanying data to start with.
```

2023-09-14 06:59 UTC, Ben2022 commented on static/autocomplete.js
> +  /* execute a function presses a key on the keyboard */
Can you rephrase this, please?

2023-09-14 06:59 UTC, Ben2022 commented on static/initialize.js
> + * @fileoverview This file contains variables that are needed for the traceablility vieuwer.
```suggestion
 * @fileoverview This file contains variables that are needed for the traceability viewer.
```

2023-09-14 06:59 UTC, Ben2022 commented on static/initialize.js
> +// for (let [key,value] of Object.entries(config["link_colours"])){
Can we clean that up?

2023-09-14 06:59 UTC, Ben2022 commented on static/initialize.js
> +/**
Generally speaking, I think we need more comments explaining what we do.

2023-09-14 07:00 UTC, Ben2022 commented on static/legend.js
> +/**
The structure of the file is not clear to me. Is it only me or you share the same concern, @JasperCraeghs ?

2023-09-14 07:01 UTC, Ben2022 commented on static/search.js
> + * This function define a query for showing the V-model of the given ID.
```suggestion
 * This function defines a query for showing the V-model of the given ID.
```

2023-09-14 07:03 UTC, Ben2022 commented
Is it possible that we perform some unit tests in general? I will be more explicit in my next comment.

2023-09-14 07:03 UTC, Ben2022 commented on static/search.js
> +function addConnectedNodes(query){
Do we have evidence that it works as we expect?

2023-09-14 07:20 UTC, JokeWaumans commented on static/search.js
> +function addConnectedNodes(query){
Evidence of what type? If the graph database is correctly built?

2023-09-14 07:21 UTC, Ben2022 commented on static/search.js
> +function addConnectedNodes(query){
Have we tested it and if yes, can we commit also the tests?

2023-09-14 07:29 UTC, JokeWaumans commented on static/search.js
> +function addConnectedNodes(query){
It works on the local build of a product, so there are no real tests.

2023-09-14 10:32 UTC, Ben2022 commented on static/search.js
> +function addConnectedNodes(query){
@JasperCraeghs , do we have unit tests for the traceability plugin?

2023-09-15 08:10 UTC, JokeWaumans commented on autocomplete.py
> +
I think it is resolved in 9834004

2023-09-15 08:20 UTC, JasperCraeghs commented on static/search.js
> + * This function will update the graph with the new nodes and links. It will restart the simulation.
```suggestion
 * Updates the nodes and links of the graph and restarts the simulation.
```
Please update every docstring to use this style of wording.

2023-09-15 08:24 UTC, JasperCraeghs commented on static/vis_D3.css
> +  font: 16px Arial;
```suggestion
  font-size: 16px;
  font-family: Lato, Helvetica Neue, Arial, sans-serif;
```
Let's use the same font-family as sphinx-rtd-theme.

2023-09-15 08:41 UTC, JasperCraeghs commented on autocomplete.py
> +Copyright (c) 2022 Melexis
This copyright notice should be removed as we rely on the [`LICENSE`](https://github.com/melexis/traceability-viewer/blob/main/LICENSE) file, right @Letme ?

2023-09-15 08:50 UTC, JasperCraeghs commented on config.yml
> +link_colours:
```suggestion
link_colors:
```
Let's use American English. Please update all other occurrences. Or does a  dependency like D3js use "colour" everywhere?

2023-09-15 08:54 UTC, Letme commented on autocomplete.py
> +Copyright (c) 2022 Melexis
you want a single LICENSE file per repository and nothing on top of the files. Also make sure its 2023, not 2022.

2023-09-15 08:55 UTC, Letme commented on autocomplete.py
> +with open("config.yml", "r", encoding="utf-8") as open_file:
Not sure why you do not make a function here and just have all the code/execution in the single file. Use functions (`def main:` if nothing else)

2023-09-15 08:56 UTC, Letme commented on make_html.py
> +    html = f"""
I suggest you use mako template for such HTML blobs. It will make it easier for future generations to change and it will not add so many tabs infront.

2023-09-15 08:56 UTC, JasperCraeghs commented on config.yml
> +  passes: "#2b00ff"
Did you use a random color picker tool? I suggest using green for passes/passed_by and red for fails/failed_by and orange for skiped/skipped_by. These relationships are associated with specific colors. For other relationships, the colors matters less I would say.

2023-09-15 08:56 UTC, Letme commented on make_html.py
> +with graphdb.session() as session:
Again, make sure you use functions.

2023-09-15 08:57 UTC, JasperCraeghs commented on config.yml
> +  is_attribute_of: "#009900"
Did you implement a warning when the traceable collection contains a relationship that is not configured here?

2023-09-15 09:51 UTC, JokeWaumans commented on static/autocomplete.js
> +  /* execute a function presses a key on the keyboard */
Resolved in 21e0e1ffc0022ce7df3de6db9a3677760fc1e691

2023-09-25 11:38 UTC, JasperCraeghs commented on make_neo4j_db.py
> +                            if rel in list(self.config_dict["link_colors"].keys()):
```
color = self.config_dict["link_colors"].get(rel, "#808080")
session.execute_write(self.add_relationship, id1, id2, rel, color)
```

2023-09-25 11:40 UTC, JasperCraeghs commented on make_neo4j_db.py
> +                attr = item["attributes"]
`attributes`

2023-09-25 11:44 UTC, JasperCraeghs commented on make_neo4j_db.py
> +            attributes (json): JSON string of the attributes of the document item
```suggestion
            attributes (str): JSON string of the attributes of the document item
```

2023-09-25 12:01 UTC, JasperCraeghs commented on make_neo4j_db.py
> +    def add_group_and_color(tx, id_item, group, color):
add_item_to_group

2023-09-25 12:14 UTC, JasperCraeghs commented on make_neo4j_db.py
> +                if id1.startswith(self.groups[0]):
```
for group in groups:
    if re.match(group, id1):
        selected_group = group
        selected_color = self.config_dict["group_colors"][group]
        break
else:
    selected_group = "Others"
    selected_color = "#000000"
session.execute_write(self.add_group_and_color, id1, selected_group, selected_color)
```
Let's use [`re.match`](https://docs.python.org/3/library/re.html#re.match) instead of `str.startswith` for added flexibility. Users of mlx.traceability are used to defining regular expressions. Please document this feature.

2023-09-28 08:31 UTC, JasperCraeghs commented on README.md
> +If docker-compose is not istalled yet, install it with the `sudo apt install docker-compose` command.
```suggestion
If docker-compose is not installed yet, install it with the `sudo apt install docker-compose` command.
```
Please provide a link to the official documentation of Docker Compose and any other tool, e.g. Neo4j.

2023-09-28 08:32 UTC, JasperCraeghs commented on README.md
> +Firstly, install the python packages with command:
```suggestion
Firstly, install the Python dependencies with [pip](https://pip.pypa.io/en/stable/):
```

2023-09-28 08:44 UTC, JasperCraeghs commented
> There are still some bugs that need to be fixed, but the main goal is working.

Please document the list of known bugs.

2023-09-28 09:30 UTC, JasperCraeghs commented on README.md
> +The groups with their corresponding colors.
Can we combine the `filters` and `group_colors` in the configuration into a single map/dictionary? Python>=3.6 [preserves the order of dictionaries](https://stackoverflow.com/questions/1867861/how-to-keep-keys-values-in-same-order-as-declared). Does this work when reading a YAML map, though?

2023-09-28 09:38 UTC, JasperCraeghs commented on config.yml
> +project: MLX{product}
Is this configuration value used by the tool? If so, document it in the readme.

2023-09-28 10:00 UTC, JasperCraeghs commented on README.md
> +This is the path to the JSON database of a local build (doc folder) of a Melexis product.
This will be an open source tool, so it will be available to every company. The example config.yml can contain some Melexis-specific configuration, but the documentation for chapter Configuration should be exhaustive and generic enough for everyone. I suggest simply referencing the Configuration section here.

`Edit the example [configuration file](#configuration).`

2023-09-28 10:30 UTC, JasperCraeghs commented on config.yml
> +json_folder: [*BASE_URL, *PRODUCT, /database.json]
I would rename this configuration value to `json_database` or `traceability_export`. 

`/database.json` should not contain a `/`. Then, every element of the list is a part of the path, which you can assemble with [`pathlib.PurePosixPath.joinpath`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.joinpath).

2023-09-28 10:35 UTC, JasperCraeghs commented on README.md
> +The product number and the BASE_URL contains the path to the build/doc folder of that product.
Please explain the syntax for defining and using variables.

Support for environment variables is needed for easy integration in CI.

2023-09-28 10:50 UTC, JasperCraeghs commented on config.yml
> +URL: [*BASE_URL, *PRODUCT, /html/document.html#id]
```suggestion
html_dir: [*BASE_URL, *PRODUCT, html]
```
`document.html#id` is unnecessary in the configuration. `node_clicked` in forcegraph.js can append the document name and node ID to `html_dir`.

2023-09-28 10:56 UTC, JasperCraeghs commented on README.md
> +The path to the HTML documentation. Depending on the file structure, the ending could be changed to `/rom/html/document.html#id` in case of ROM.
Please clarify that you mean the HTML documentation generated by mlx.traceability, not `make_html.py`.

Is a URL to documentation hosted on a webserver supported?

The `rom` subfolder is Melexis-specific and I don't think we will use this. I would not mention it here.

2023-09-28 11:25 UTC, JasperCraeghs commented on autocomplete.py
> +    words.append(w)
You could use this list as the initial value instead of `words = []` on L28. Or does the order of the list elements matter?

2023-09-28 11:38 UTC, JasperCraeghs requested changes

2023-09-28 11:38 UTC, JasperCraeghs commented on autocomplete.py
> +    words.append(l)
Use [`list.extend`](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists)

2023-09-28 11:38 UTC, JasperCraeghs commented on README.md
> +The path to the exported database.json file. This is the BASE_URL followed by the product number, ending with /database.json.
In addition to support for a local file, we should support the download of this file when it's hosted on a webserver. See https://docs.python.org/3/library/urllib.parse.html#url-parsing

2023-09-29 09:33 UTC, JasperCraeghs commented on make_html.py
> +                <input placeholder="SWARCH_" type="text" id="search">
`SWARCH_` is Melexis-specific. What's the value of a placeholder here?

2023-09-29 09:53 UTC, JasperCraeghs commented on static/initialize.js
> +  "guaranteed_by", "ext_polarion_reference", "test_setup_used", "is_attribute_of"];
This must be configurable.

2023-10-20 13:47 UTC, JasperCraeghs commented on static/search.js
> +function addConnectedNodes(query){
The traceability plugin has some unit tests. We rely a lot on the build of the example documentation. If a new feature is added, it is showcased in the example doc and the HTML is inspected manually.

2023-11-17 12:41 UTC, JokeWaumans commented on static/initialize.js
> +/**
Resolved in 7d3ac97116fba4f7045d79a4d5615638dc7a38e0

2023-11-17 12:41 UTC, JokeWaumans commented on autocomplete.py
> +Copyright (c) 2022 Melexis
Resolved in 82c6d6cb426b2a0c6b57a23fa560c40329732620

2023-11-17 12:41 UTC, JokeWaumans commented on config.yml
> +link_colours:
Resolved in 83a206dcb8dc459fb807e351a7600c2d92024b89

2023-11-17 12:41 UTC, JokeWaumans commented on config.yml
> +  is_attribute_of: "#009900"
No, when a relationship is not configured, it will get a gray color.

2023-11-17 12:41 UTC, JokeWaumans commented on config.yml
> +project: MLX{product}
`project: MLX{product}` is not used, thus can be removed

2023-11-17 12:41 UTC, JokeWaumans commented on make_html.py
> +                <input placeholder="SWARCH_" type="text" id="search">
Yes, it is Melexis-specific, and it is no longer relevant because you need to enter a full ID.

2023-11-17 12:41 UTC, JokeWaumans commented on config.yml
> +  passes: "#2b00ff"
Changed the colors in 495818dd280896df70bbd32ab1bd852ad60fcd85

2023-11-17 12:41 UTC, JokeWaumans commented on make_neo4j_db.py
> +                attr = item["attributes"]
Resolved in c44e254bb241c8a208f74b8312301350afdbfec8

2023-11-17 12:41 UTC, JokeWaumans commented on README.md
> +The groups with their corresponding colors.
Not relevant anymore, see #2

2024-02-14 10:33 UTC, JasperCraeghs commented on make_html.py
> +    html = f"""
Resolved in #2 by using Vue components

2024-02-14 10:38 UTC, JasperCraeghs commented
Closing in favor of #2, which uses Django for the backend and Vue for the frontend.

2024-02-14 10:38 UTC, closed without merging